### ISSUE TITLE
How to change the selected date externally

### ISSUE THREAD

**Issue by lobin-z0x50** [limbara/vue-time-date-range-picker#38]
Hello.
I am using `date-picker`.
I can set initial values by specifying `initial-dates`, but is there any way to change the dates further externally after that?
I would like to be able to binding a Date object.

**Comment by limbara** [comment]
hi @lobin-z0x50, i don't think we have any other way to change values of selected date externally, also what do you mean by binding a Date object ? is it reactivity when the `initial-dates` change ? if that what you mean then all i could think of is using `:key="dates"` prop to force update the component

**Comment by lobin-z0x50** [comment]
hi @limbara, Thanks for your comment.
By "binding" I meant something like binding to the view-model with a feature like `v-model` commonly used in Vue.js.
How exactly do you force a component to update using `:key="dates"`?

**Comment by limbara** [comment]
its' been a long time since i use vue, but from what i read from their [v-model guide](https://vuejs.org/guide/components/v-model.html), it's just a shorthand for a `prop` and emit event `update:prop`. You can force update a component just by passing a different value to :key bind to the component. In this case below i passed a `dates1` Object, because i want it to change when my `dates1` value change

```vue
<template>
  <div>
    <date-picker :dateInput="dateInput" :initialDates="dates1" :key="dates1" />
    <button @click="changeDate">
      Test
    </button>
  </div>
</template>

<script>
...imports 

export default {
  components: {
    DatePicker,
  },
  data() {
    return {
      dateInput: {
        placeholder: 'Select Date',
        required: true,
      },
      dates1: [new Date('2022 09 01 00:00'), new Date('2022 09 03 23:59')],
    };
  },
  methods: {
    changeDate() {
      this.dates1 = [new Date('2023 09 01 00:00'), new Date('2023 09 15 00:00')];
    },
  },
};
</script>
```

**Comment by lobin-z0x50** [comment]
Thank you for your explanation!
I did indeed get the expected behavior with the `:key` method.
However, I keep getting the following warning in the developer console
Is there any workaround?
```
[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.
```

**Comment by limbara** [comment]
hhmm, maybe you could try formatting this array of Date object into string maybe, like in my example above into `"2023-09-01 00:00,2023-09-15 00:00"`. But instead of putting this format directly in the prop, you could use `computed` to format it first. If it doesn't work then you can  just format it directly in the `:key` prop `:key="toKey(dates)"` . Indeed it's not the cleanest way for eyes to see, but it works

**Comment by lobin-z0x50** [comment]
Thank you very much!
The method you presented worked well!

I implemented the toKey method to return a JSON string.
```js
const vueApp = new Vue({
  el: '#vue-app',
  components: {
    DatePicker,
    CalendarDialog,
  },
  data() {
    return {
      timeRange: [new Date(), new Date()],
    }
  },
  computed: {
    timeRangeAsKey() {
      return JSON.stringify(this.timeRange)
    }
  }
}
```
```html
<div class="">
  <date-picker :initial-dates="timeRange"
               :key="timeRangeAsKey"
               :inline="false"
                 ...
               />
</div>
```

Now, when I set a value to the `timeRange` property externally, it is reflected in the `vue-time-date-range-picker`.
